package infoP;
// Generated Jan 26, 2017 1:53:48 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String gpa;

    public Student() {
    }

	
    public Student(String name, String surname) {
        this.name = name;
        this.surname = surname;
    }
    public Student(String name, String surname, String gpa) {
       this.name = name;
       this.surname = surname;
       this.gpa = gpa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getGpa() {
        return this.gpa;
    }
    
    public void setGpa(String gpa) {
        this.gpa = gpa;
    }




}


